# Generated by Django 3.1.7 on 2021-10-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.URLField(default='https://res.cloudinary.com/dxeibizaf/image/upload/v1616122320/auctions/27_a1hx87.jpg'),
        ),
    ]
